apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: azureoperator-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: azureoperator-leader-election-role
  namespace: azureoperator-system
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - configmaps/status
  verbs:
  - get
  - update
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: azureoperator-manager-role
rules:
- apiGroups:
  - azure.microsoft.com
  resources:
  - cosmosdbs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - azure.microsoft.com
  resources:
  - eventhubnamespaces/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - azure.microsoft.com
  resources:
  - keyvaults/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - azure.microsoft.com
  resources:
  - resourcegroups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - azure.microsoft.com
  resources:
  - sqldatabases/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - watch
- apiGroups:
  - azure.microsoft.com
  resources:
  - rediscaches/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - azure.microsoft.com
  resources:
  - consumergroups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - azure.microsoft.com
  resources:
  - eventhubs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - azure.microsoft.com
  resources:
  - eventhubnamespaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - azure.microsoft.com
  resources:
  - keyvaults
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - azure.microsoft.com
  resources:
  - sqlfirewallrules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - azure.microsoft.com
  resources:
  - sqlfirewallrules/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - azure.microsoft.com
  resources:
  - storages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - azure.microsoft.com
  resources:
  - sqlservers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apps
  resources:
  - deployments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - azure.microsoft.com
  resources:
  - consumergroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - azure.microsoft.com
  resources:
  - sqlservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - azure.microsoft.com
  resources:
  - storages/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - azure.microsoft.com
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - azure.microsoft.com
  resources:
  - eventhubs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - azure.microsoft.com
  resources:
  - rediscaches
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - azure.microsoft.com
  resources:
  - sqldatabases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - azure.microsoft.com
  resources:
  - cosmosdbs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - azure.microsoft.com
  resources:
  - resourcegroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: azureoperator-proxy-role
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: azureoperator-leader-election-rolebinding
  namespace: azureoperator-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: azureoperator-leader-election-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: azureoperator-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: azureoperator-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: azureoperator-manager-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: azureoperator-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: azureoperator-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: azureoperator-proxy-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: azureoperator-system
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "8443"
    prometheus.io/scheme: https
    prometheus.io/scrape: "true"
  labels:
    control-plane: controller-manager
  name: azureoperator-controller-manager-metrics-service
  namespace: azureoperator-system
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    control-plane: controller-manager
---
apiVersion: v1
kind: Service
metadata:
  name: azureoperator-webhook-service
  namespace: azureoperator-system
spec:
  ports:
  - port: 443
    targetPort: 443
  selector:
    control-plane: controller-manager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: controller-manager
  name: azureoperator-controller-manager
  namespace: azureoperator-system
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      containers:
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=10
        image: gcr.io/kubebuilder/kube-rbac-proxy:v0.4.0
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
      - args:
        - --metrics-addr=127.0.0.1:8080
        command:
        - /manager
        env:
        - name: AZURE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: AZURE_CLIENT_ID
              name: azureoperatorsettings
        - name: AZURE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: AZURE_CLIENT_SECRET
              name: azureoperatorsettings
        - name: AZURE_TENANT_ID
          valueFrom:
            secretKeyRef:
              key: AZURE_TENANT_ID
              name: azureoperatorsettings
        - name: AZURE_SUBSCRIPTION_ID
          valueFrom:
            secretKeyRef:
              key: AZURE_SUBSCRIPTION_ID
              name: azureoperatorsettings
        - name: REQUEUE_AFTER
          value: "30"
        image: docker.io/frodopwns/ctest:3
        name: manager
        ports:
        - containerPort: 443
          name: webhook-server
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
      terminationGracePeriodSeconds: 10
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: webhook-server-cert
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: azureoperator-serving-cert
  namespace: azureoperator-system
spec:
  commonName: azureoperator-webhook-service.azureoperator-system.svc
  dnsNames:
  - azureoperator-webhook-service.azureoperator-system.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: azureoperator-selfsigned-issuer
  secretName: webhook-server-cert
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: azureoperator-selfsigned-issuer
  namespace: azureoperator-system
spec:
  selfSigned: {}
